name: xynergycapital.com
favicon: null
layout_spectrum: 0.24984
typography_spectrum: 0.50308
title: Xynergy Commercial Capital
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#22335e'
    - '#2262ac'
    - '#9d6a4d'
    - '#e4c898'
    - '#fcfdf9'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.08511748886667192
purpose: []
