name: xynergycapital.com
favicon: null
layout_spectrum: 0.2405602321960032
typography_spectrum: 0.458541392814368
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3009916839655489
  lightness: 0.788590072421357
  saturation: 0.35108531592413783
  rhythmicContrast: 0.08511748886667192
purpose: []
