name: xynergycapital.com
favicon: null
layout_spectrum: 0.00541
typography_spectrum: 0.50308
title: Xynergy Commercial Capital
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a8a9ad'
    - '#1c4f84'
    - '#156eb0'
    - '#d2d3d5'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.08511748886667192
purpose: []
