name: xynergycapital.com
favicon: null
layout_spectrum: 0.49222
typography_spectrum: 0.18761
title: Xynergy Commercial Capital
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#02568a'
    - '#069edb'
    - '#5d7fae'
    - '#000000'
    - '#000080'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.35108531592413783
  rhythmicContrast: 0.08511748886667192
purpose: []
